# dont mind this, this was made to check if the changes still reflected even after getting an std err

def main(args = None):
    print(2)

if __name__ == '__main__':
    main()